name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Check code formatting with Black
        run: |
          source .venv/bin/activate
          black --check src/ tests/

      - name: Run Pylint
        env:
          PYTHONPATH: .
        run: |
          source .venv/bin/activate
          pylint src/ tests/

      - name: Run Pytest
        env:
          PYTHONPATH: .
        run: |
          source .venv/bin/activate
          python -m pytest tests/

      
      - name: Run tests with coverage
        env:
          PYTHONPATH: .
        run: |
          source .venv/bin/activate
          python -m pytest --cov=src --cov-fail-under=55 tests/

      
      - name: Generate coverage badge
        run: |
          source .venv/bin/activate
          mkdir -p .github/coverage
          coverage-badge -o .github/coverage/coverage.svg -f

      - name: Update README with coverage percentage
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          source .venv/bin/activate
          COVERAGE=$(python -m pytest --cov=src --cov-report=term tests/ | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
          sed -i "s/Current coverage: ~[0-9]\+%/Current coverage: ~${COVERAGE}%/" README.md

      - name: Commit and push coverage badge and README
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/coverage/coverage.svg README.md
          git diff --staged --quiet || git commit -m "Update coverage badge and README [skip ci]"
          git push