name: Release

on:
  push:
    tags:
      - 'v*.*.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract changelog entry
        id: changelog
        run: |
          TAG="${GITHUB_REF_NAME}"
          TITLE="grep-python $TAG"
          BODY=$(awk "/^## \\[${TAG//./\\.}\\]/,/^## \\[/" CHANGELOG.md | sed '$d')
          if [ -z "$BODY" ]; then
            BODY="Release $TAG"
          fi
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.changelog.outputs.title }}
          body: ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}